package edu.sjsu.cmpe275.lab2.entities;

// Generated Nov 2, 2015 9:04:29 PM by Hibernate Tools 3.4.0.CR1

import java.util.List;

import javax.persistence.Column;
import javax.persistence.Embedded;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.OneToMany;
import javax.persistence.Transient;
import javax.persistence.ManyToOne;
import javax.persistence.ManyToMany;
import javax.persistence.*;

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Id;
import javax.persistence.Table;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlAttribute;

/**
 * Person generated by hbm2java
 */

@XmlRootElement(name = "person")
@Entity
@Table(name = "Person", catalog = "CMPE275_LAB2")
public class Person implements java.io.Serializable {

	private Integer personId;
	private String firstName;
	private String lastName;
	private String email;
	private String description;

	@Transient
	@Embedded
	private Address address;

	private Organization organization;


	/*@ManyToMany
	@JoinTable(name="FRIENDSHIP",
	 joinColumns=@JoinColumn(name="PersonID"),
	 inverseJoinColumns=@JoinColumn(name="FriendId")
	)
	private List<Person> friends;*/

	public Person() {
	}

	public Person(String firstName, String lastName) {
		this.firstName = firstName;
		this.lastName = lastName;
	}

	public Person(String firstName, String lastName, String email,
			String description, Address address, Organization organization) {
		this.firstName = firstName;
		this.lastName = lastName;
		this.email = email;
		this.description = description;
		this.address = address;
		this.organization = organization;
	}

	@XmlAttribute
	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "PersonID", unique = true, nullable = false)
	public Integer getPersonId() {
		return this.personId;
	}

	public void setPersonId(Integer personId) {
		this.personId = personId;
	}

	@XmlAttribute
	@Column(name = "FirstName", nullable = false, length = 30)
	public String getFirstName() {
		return this.firstName;
	}

	public void setFirstName(String firstName) {
		this.firstName = firstName;
	}

	@XmlAttribute
	@Column(name = "LastName", nullable = false, length = 30)
	public String getLastName() {
		return this.lastName;
	}

	public void setLastName(String lastName) {
		this.lastName = lastName;
	}

	@XmlAttribute
	@Column(name = "Email", length = 30)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@XmlAttribute
	@Column(name = "Description", length = 30)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@XmlAttribute
	public Address getAddress() {
		return address;
	}

	public void setAddress(Address address) {
		this.address = address;
	}

/*	@XmlAttribute
	public List<Person> getFriends() {
		return friends;
	}

	public void setFriends(List<Person> friends) {
		this.friends = friends;
	}*/

	@XmlAttribute
	@ManyToOne
	@JoinColumn(name = "organizationId")
	public Organization getOrganization() {
		return organization;
	}

	public void setOrganization(Organization organization) {
		this.organization = organization;
	}

}
